### PR TITLE
Remove transfer cooldown from characters

### PR DESCRIPTION
**Pull request by brian-man**

### CODE REVIEW

**Comment by seiyria** [comment]
ui-wise this is probably fine but it does need to pass the build

**Comment by gmigson** [comment]
saludos. soy usuario de CRYTOBLADES, 
realice un enlistado en el market de un personaje y ahora no aparece en ningún lado..

**Comment by seiyria** [comment]
@gmigson this issue tracker is EN only. also, it's not for general users.

**Comment by brian-man** [comment]
@KR Please check the contract stuff carefully.  I don't fully grok the proxy upgradability rules.

**Review by raymond-h — APPROVED** [review]

**Pull request merged**
