### PR TITLE
added loader to Forge Button Initialization

### PR DESCRIPTION
**Pull request by Spintacle123**
### All Submissions

* [ ] Can you post a screenshot of your changes (if applicable)?
image

### New Feature Submissions

* [ ] Does this relate to an existing issue, or has it been talked about prior to being done (if a major change)?

### Notes

Please note, your code must pass all tests and lint checks before it can be merged.

### PR Description

Added Loader for Forge Button Cost Initialization

### Testing

Has the code been tested, or does it need double checking?

### CODE REVIEW

**Review by kevinunger — APPROVED** [review]
looks good!

**Comment by kevinunger** [comment]
aweseome!
One small change: 
Can you change the btn color of the skeleton to blue?
brown here
image
but blue here
image

**Comment by Spintacle123** [comment]
sure will do.

**Review by kevinunger — APPROVED** [review]
lgtm!

**Pull request merged**
