### PR TITLE
PvP

### PR DESCRIPTION
**Pull request by Nyawmeowww**
### All Submissions

Still under development

### New Feature Submissions

Issue #428  - pvp

### Notes

Please note, your code must pass all tests and lint checks before it can be merged.

### PR Description

This is the pull request for pvp-frontend, but moving forward the contract code can also be merged in it.

### CODE REVIEW

**Comment by seiyria** [comment]
Why was this closed?

**Comment by Nyawmeowww** [comment]
> Why was this closed?

I was trying to create a new branch for pvp, but that will be too much work. Anw, the `package-lock.json` got included in the push blocking the checks. Upon checking my .`gitignore` after pulling from main, `package-lock.json` is not in there.

**Comment by seiyria** [comment]
That's because I removed it from the .gitignore. package-lock should be committed.

**Comment by Nyawmeowww** [comment]
> That's because I removed it from the .gitignore. package-lock should be committed.

Alright. I'll proceed with the fix on the conflicts

**Comment by Nyawmeowww** [comment]
Conflicts are now fixed. Checks have passed.

**Comment by 5runz** [comment]
Add betting system in pvp the winner takes 50 percent of the price and the another 20 percent goes to rewards pool for extra income

**Comment by seiyria** [comment]
@5runz this is not the place for ideas. Ideas go in hellonext.

**Comment by Nyawmeowww** [comment]
### What's changed?

- Adjust the UI to support shields and incoming inventory items that can be equipped to fight in the "Arena" (e.g. boots, armor, trinkets and potions, helmet, etc)
- Separated the Inventory into multiple tabs based on category
- Created a tab selector for chosen character so that the user doesn't have to use the slider (which is not user-friendly given that the player wants to choose the last character)
- Created a droppable div for equipped items in character section

### What's coming?

- Drag-and-drop actions
- Setup data receivers for incoming contract objects (these are placeholders, mocked and not final)

**Comment by Nyawmeowww** [comment]
### Close Pull Request

*Creating a new PR  to remove the unnecessary commits*

**Pull request closed without merging**
