### PR TITLE
fix(combat): stamina bar on compressed screen should be wider

### PR DESCRIPTION
**Pull request by jayehernandez**
### All Submissions

* [x] Can you post a screenshot of your changes (if applicable)?
Screen Shot 2021-08-01 at 11 36 09 AM
Screen Shot 2021-08-01 at 12 15 16 PM

### New Feature Submissions

* [x] Does this relate to an existing issue, or has it been talked about prior to being done (if a major change)?
References #571

### Notes

Please note, your code must pass all tests and lint checks before it can be merged.

### PR Description

A simple fix for the stamina dropdown being too narrow on larger screens, you either have to zoom out, or click on the dropdown to see the stamina you chose which is a bit of a hassle. I only changed the CSS for when there is a `selectedWeaponId`. Do let me know if the UI is fine too!

### CODE REVIEW

**Comment by seiyria** [comment]
Is there currently an issue open for this I can tag it to?

**Review by seiyria — CHANGES_REQUESTED** [review]
needs to pass linter

**Comment by jayehernandez** [comment]
@seiyria there's no issue yet, can I create one?

**Comment by seiyria** [comment]
@jayehernandez sure, as long as you link it to this so it can be found

**Comment by jayehernandez** [comment]
The error from the CLI doesn't seem to be related to the code.
image

I ran `npm run lint` locally and there weren't any lint errors? Not sure if I'm missing something.
image

**Comment by seiyria** [comment]
@jayehernandez you'll need to merge the latest main, this was fixed yesterday.

**Review by seiyria — APPROVED** [review]

**Pull request merged**
