### PR TITLE
forgot to apply discount to this.forgeCost

### PR DESCRIPTION
**Pull request by kevinunger**
Apply 20% discount, in calc to disable checkbox

### CODE REVIEW

**Review by seiyria — APPROVED** [review]

**Review by seiyria — CHANGES_REQUESTED** [review]
It would be nice to have all of this wrapped in BN functions instead of number functions

**Comment by kevinunger** [comment]
@seiyria 
like that? f8c8a234a45c51986d59048260f0a0cf80a08570

**Comment by seiyria** [comment]
@kevinunger looks right to me! @raymond-h if it looks good for what you wanted lets merge it

**Comment by raymond-h** [comment]
Seems fine enough to me.

**Review by raymond-h — APPROVED** [review]

**Pull request merged**
