### PR TITLE
Character bar revamp

### PR DESCRIPTION
**Pull request by wintersummermint**
### All Submissions

* [ ] Can you post a screenshot of your changes (if applicable)?
Current : 
Screen Shot 2021-07-14 at 1 56 22 AM

Submission : 
character switches
My Goal is to have CB cleaner look and professional

Next potential release just needs approval from Kroge is the card characters im working on... 

character CB card

### New Feature Submissions

* [ ] Does this relate to an existing issue, or has it been talked about prior to being done (if a major change)?

### Notes

Please note, your code must pass all tests and lint checks before it can be merged.

### PR Description

(insert description here)

### CODE REVIEW

**Comment by seiyria** [comment]
Does this factor in new features such as the gradiented background of the character selectors?

**Comment by wintersummermint** [comment]
Oh, i see what you mean, theres progress bar inside that of that is stamina bar. i'll take a look what can i do for that in UI

**Comment by kcper** [comment]
I see something like that, can we force the level info to be in one line like in your gif?
image

**Comment by wintersummermint** [comment]
Yes, let me update this PR

**Comment by wintersummermint** [comment]
Screen Shot 2021-07-14 at 2 55 06 PM

Updated to be a stamina bar inside

**Comment by seiyria** [comment]
I'm going to tentatively accept this. We have some further changes to make, but they don't have to hold this PR up. Thanks!

**Review by seiyria — APPROVED** [review]

**Pull request merged**
