### PR TITLE
feat(combat): show gas result post-combat

### PR DESCRIPTION
**Pull request by caiquejjx**
### All Submissions

* [X] Can you post a screenshot of your changes (if applicable)?

WIN:
image

LOSE:
image

### New Feature Submissions

* [x] Does this relate to an existing issue, or has it been talked about prior to being done (if a major change)?
https://github.com/CryptoBlades/cryptoblades/issues/208

### Notes

Please note, your code must pass all tests and lint checks before it can be merged.

### PR Description
Added gas used info in combat results

### CODE REVIEW

**Comment by caiquejjx** [comment]
@seiyria based on that site https://bscgas.info I used the gas price as 5 since most of the time the price is 5 and I believe this feature is supposed to be an approximation but I could easily change to an api call that gets the current BSC gas price prediction, do u think it's necessary to use the api?

**Comment by ed3ath** [comment]
use web3.eth.getTransaction() to get the gas price and web3.eth.getTransactionReceipt() to get the gas used

that's what I used on my tracker. it's 100% accurate

**Comment by caiquejjx** [comment]
The getTransaction might be a good idea for the gas price but the getTransactionReceipt I don't think it's necessary since the transaction itself already returns the gas used

**Comment by ed3ath** [comment]
> The getTransaction might be a good idea for the gas price but the getTransactionReceipt I don't think it's necessary since the transaction itself already returns the gas used

yeah. so all good? :D

**Comment by caiquejjx** [comment]
yep, gonna implement the getTransaction and commit, thanks!

**Review by seiyria — APPROVED** [review]

**Review by seiyria — APPROVED** [review]

**Pull request merged**
