### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by Sellie96**
Brought onto repo from external fork. Feel free to finish

### CODE REVIEW

**Comment by Sellie96** [comment]
Requires Translations + Mobile optimization

**Comment by kevinunger** [comment]
When initially loading the dashboard or refreshing, it doesn't recognize that I've got characters
image

**Comment by Sellie96** [comment]
@Spintacle123 There is still a build error on this. Data type issue on raid data

**Comment by Spintacle123** [comment]
> @Spintacle123 There is still a build error on this. Data type issue on raid data

copy. checking it

**Review by Spintacle123 — APPROVED** [review]

**Pull request merged**
